FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt setup.py ./
COPY src/ ./src/
COPY etl/ ./etl/
COPY data/ ./data/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "etl/load_health_indicators.py"]
